const usa = {name:'USA', png:'usa', list:[
    {name:"Alabama", capital:"Montgomery", info:"The Yellowhammer State", color:1},
    {name:"Alaska", capital:"Juneau", info:"The Last Frontier", color:2},
    {name:"Arizona", capital:"Phoenix", info:"The Grand Canyon State", color:3},
    {name:"Arkansas", capital:"Little Rock", info:"The Natural State", color:4},
    {name:"California", capital:"Sacramento", info:"The Golden State", color:5},
    {name:"Colorado", capital:"Denver", info:"The Centennial State", color:6},
    {name:"Connecticut", capital:"Hartford", info:"The Constitution State", color:7},
    {name:"Delaware", capital:"Dover", info:"The First State", color:8},
    {name:"Florida", capital:"Tallahassee", info:"The Sunshine State", color:9},
    {name:"Georgia", capital:"Atlanta", info:"The Peach State", color:10},
    {name:"Hawaii", capital:"Honolulu", info:"The Aloha State", color:11},
    {name:"Idaho", capital:"Boise", info:"The Gem State", color:12},
    {name:"Illinois", capital:"Springfield", info:"The Prairie State", color:13},
    {name:"Indiana", capital:"Indianapolis", info:"The Hoosier State", color:14},
    {name:"Iowa", capital:"Des Moines", info:"The Hawkeye State", color:15},
    {name:"Kansas", capital:"Topeka", info:"The Sunflower State", color:16},
    {name:"Kentucky", capital:"Frankfort", info:"The Bluegrass State", color:17},
    {name:"Louisiana", capital:"Baton Rouge", info:"The Pelican State", color:18},
    {name:"Maine", capital:"Augusta", info:"The Pine Tree State", color:19},
    {name:"Maryland", capital:"Annapolis", info:"The Old Line State", color:20},
    {name:"Massachusetts", capital:"Boston", info:"The Bay State", color:21},
    {name:"Michigan", capital:"Lansing", info:"The Great Lakes State", color:22},
    {name:"Minnesota", capital:"Saint Paul", info:"The North Star State", color:23},
    {name:"Mississippi", capital:"Jackson", info:"The Magnolia State", color:24},
    {name:"Missouri", capital:"Jefferson City", info:"The Show-Me State", color:25},
    {name:"Montana", capital:"Helena", info:"The Treasure State", color:26},
    {name:"Nebraska", capital:"Lincoln", info:"The Cornhusker State", color:27},
    {name:"Nevada", capital:"Carson City", info:"The Silver State", color:28},
    {name:"New Hampshire", capital:"Concord", info:"The Granite State", color:29},
    {name:"New Jersey", capital:"Trenton", info:"The Garden State", color:30},
    {name:"New Mexico", capital:"Santa Fe", info:"The Land of Enchantment", color:31},
    {name:"New York", capital:"Albany", info:"The Empire State", color:32},
    {name:"North Carolina", capital:"Raleigh", info:"The Tar Heel State", color:33},
    {name:"North Dakota", capital:"Bismarck", info:"The Peace Garden State", color:34},
    {name:"Ohio", capital:"Columbus", info:"The Buckeye State", color:35},
    {name:"Oklahoma", capital:"Oklahoma City", info:"The Sooner State", color:36},
    {name:"Oregon", capital:"Salem", info:"The Beaver State", color:37},
    {name:"Pennsylvania", capital:"Harrisburg", info:"The Keystone State", color:38},
    {name:"Rhode Island", capital:"Providence", info:"The Ocean State", color:39},
    {name:"South Carolina", capital:"Columbia", info:"The Palmetto State", color:40},
    {name:"South Dakota", capital:"Pierre", info:"Mount Rushmore State", color:41},
    {name:"Tennessee", capital:"Nashville", info:"The Volunteer State", color:42},
    {name:"Texas", capital:"Austin", info:"The Lone Star State", color:43},
    {name:"Utah", capital:"Salt Lake City", info:"The Beehive State", color:44},
    {name:"Vermont", capital:"Montpelier", info:"The Green Mountain State", color:45},
    {name:"Virginia", capital:"Richmond", info:"The Old Dominion", color:46},
    {name:"Washington", capital:"Olympia", info:"The Evergreen State", color:47},
    {name:"West Virginia", capital:"Charleston", info:"The Mountain State", color:48},
    {name:"Wisconsin", capital:"Madison", info:"The Badger State", color:49},
    {name:"Wyoming", capital:"Cheyenne", info:"The Equality State", color:50}
]};

const europe = {name:'Europe', png:'europe', default:true, list:[
    {name:"Albania", capital:"Tiranë", info:"The Land of Eagles", color:1},
    {name:"Andorra", capital:"Andorra la Vella", info:"The Land of Snow", color:2},
    {name:"Armenia", capital:"Yerevan", asia:true, info:"The First Christian Nation", color:3},
    {name:"Austria", capital:"Vienna", info:"The Heart of Europe", color:4},
    {name:"Azerbaijan", capital:"Baku", asia:true, info:"The Land of Fire", color:5},
    {name:"Belarus", capital:"Minsk", info: "The Land of Lakes", color:6},
    {name:"Belgium", capital:"Brussels", info:"The Crossroads of Europe", color:7},
    {name:"Bosnia and Herzegovina", capital:"Sarajevo", key:"bosnia", info: "The Land of Diversity", color:8},
    {name:"Bulgaria", capital:"Sofia", info:"The Land of Roses", color:9},
    {name:"Croatia", capital:"Zagreb", info:"The Pearl of Adriatic", color:10},
    {name:"Cyprus", capital:"Nicosia", info:"Island of Aphrodite", color:11},
    {name:"Czechia", capital:"Prague", info:"Land of Bohemia", color:12},
    {name:"Denmark", capital:"Copenhagen", info:"The Land of Vikings", color:13},
    {name:"Estonia", capital:"Tallinn", info:"The Digital Society" ,color:14},
    {name:"Finland", capital:"Helsinki", info:"The Land of Thousand Lakes", color:15},
    {name:"France", capital:"Paris", info:"The Hexagon", color:16},
    {name:"Georgia", capital:"Tbilisi", asia:true, info:"The Land of Hospitality", color:17},
    {name:"Germany", capital:"Berlin", info:"The Engine of Europe", color:18},
    {name:"Greece" ,capital:"Athens", info:"The Cradle of Civilization", color:19},
    {name:"Hungary", capital:"Budapest", info:"The Land of the Magyars", color:20},
    {name:"Iceland", capital:"Reykjavik", info:"The Land of Fire and Ice", color:21},
    {name:"Ireland", capital:"Dublin", info:"The Emerald Isle", color:22},
    {name:"Italy", capital:"Rome", info:"The Eternal City", color:23},
    {name:"Kosovo", capital:"Pristina", info:"The Youngest European Nation", color:24},
    {name:"Latvia", capital:"Riga", info:"The Land of Amber", color:25},
    {name:"Liechtenstein", capital:"Vaduz", info:"The Microstate of Mountains", color:26,
           url:"https://www.infoplease.com/sites/default/files/i_infopls_com/images/mliecht.gif"},
    {name:"Lithuania", capital:"Vilnius", info:"The Land of Forests", color:27},
    {name:"Luxembourg", capital:"Luxembourg City", info:"The Grand Duchy", color:28},
    {name:"Malta", capital:"Valletta", info:"The Fortress Island", color:29},
    {name:"Moldova", capital:"Chisinau", info:"The Land of Wines", color:30},
    {name:"Montenegro", capital:"Podgorica", info:"The Pearl of the Adriatic", color:31},
    {name:"Netherlands", capital:"Amsterdam", info:"The Low Country", color:32},
    {name:"North Macedonia", capital:"Skopje", info:"The Land of Alexander", key:"macedonia", color:33},
    {name:"Norway", capital:"Oslo", info:"The Land of Fjords", color:34},
    {name:"Poland", capital:"Warsaw", info:"The Heart of Central Europe", color:35},
    {name:"Portugal", capital:"Lisbon", info:"The Land of Explorers", color:36},
    {name:"Romania", capital:"Bucharest", info:"The Land of Dracula", color:37},
    {name:"Serbia", capital:"Belgrade", info:"The Land of Rivers", color:38},
    {name:"Slovakia", capital:"Bratislava", info:"The Land of Castles", color:39},
    {name:"Slovenia", capital:"Ljubljana", info:"The Green Heart of Europe", color:40},
    {name:"Spain", capital:"Madrid", info:"The Land of Passion", color:41},
    {name:"Sweden", capital:"Stockholm", info:"The Land of Midnight Sun", color:42},
    {name:"Switzerland", capital:"Bern", info:"The Land of Alps", color:43},
    {name:"Turkey", capital:"Ankara", info:"The Bridge Between Continents", color:44},
    {name:"Ukraine", capital:"Kyiv", info:"The Breadbasket of Europe", color:45},
    {name:"United Kingdom", capital:"London", info:"The Land of Monarchs", color:46}
]};

const asia = {name:'Asia', png:'asia', list:[
    {name:"Afghanistan", capital:"Kabul", info:"The Graveyard of Empires", color:1},
    {name:"Armenia", capital:"Yerevan", info:"The First Christian Nation", color:2},
    {name:"Azerbaijan", capital:"Baku", info:"The Land of Fire", color:3},
    {name:"Bahrain", capital:"Manama", info:"The Island Kingdom", color:4},
    {name:"Bangladesh", capital:"Dhaka", info:"The Land of Rivers", color:5},
    {name:"Bhutan", capital:"Thimphu", info:"The Land of Happiness", color:6},
    {name:"Brunei", capital:"Bandar Seri Begawan", info:"The Abode of Peace", color:7},
    {name:"Cambodia", capital:"Phnom Penh", info:"The Land of Temples", color:8},
    {name:"China", capital:"Beijing", info:"The Middle Kingdom", color:9},
    {name:"Cyprus", capital:"Nicosia", info:"Island of Aphrodite", color:10},
    {name:"Georgia", capital:"Tbilisi", info:"The Land of Hospitality", color:11},
    {name:"India", capital:"New Delhi", info:"The Land of Diversity", color:12},
    {name:"Indonesia", capital:"Jakarta", info:"The Emerald of the Equator", color:13},
    {name:"Iran", capital:"Tehran", info:"The Land of Persia", color:14},
    {name:"Iraq", capital:"Baghdad", info:"The Cradle of Civilization", color:15},
    {name:"Israel", capital:"Jerusalem", info:"The Holy Land", color:16},
    {name:"Japan", capital:"Tokyo", info:"The Land of the Rising Sun", color:17},
    {name:"Jordan", capital:"Amman", info:"The Land of Petra", color:18},
    {name:"Kazakhstan", capital:"Astana", info:"The Steppe Nation", color:19},
    {name:"Kuwait", capital:"Kuwait City", info:"The Land of Pearls", color:20},
    {name:"Kyrgyzstan", capital:"Bishkek", info:"The Land of Mountains", color:21},
    {name:"Laos", capital:"Vientiane", info:"The Land of a Million Elephants", color:22},
    {name:"Lebanon", capital:"Beirut", info:"The Land of Cedars", color:23},
    {name:"Malaysia", capital:"Kuala Lumpur", info:"Truly Asia", color:24},
    {name:"Maldives", capital:"Malé", info:"The Tropical Paradise", color:25,
           url:"https://as1.ftcdn.net/v2/jpg/04/57/00/82/1000_F_457008282_9W8VRaUDkP9yWT2M2pZmaGF7o7Ovq8j8.jpg"},
    {name:"Mongolia", capital:"Ulaanbaatar", info:"The Land of Eternal Blue Sky", color:26},
    {name:"Myanmar", capital:"Naypyidaw", info:"The Golden Land", color:27},
    {name:"Nepal", capital:"Kathmandu", info:"The Land of Himalayas", color:28},
    {name:"North Korea", capital:"Pyongyang", info:"The Hermit Kingdom", color:29,
           url:"https://www.worldatlas.com/upload/8f/05/35/provinces-of-north-korea-map.png"},
    {name:"Oman", capital:"Muscat", info:"The Jewel of Arabia", color:30},
    {name:"Pakistan", capital:"Islamabad", info:"The Land of the Pure", color:31},
    {name:"Palestine", capital:"East Jerusalem", info:"The Holy Land", color:32,
           url:"https://cdn.britannica.com/17/201417-050-D3316841/vision-Israel-state-West-Bank-Palestinian-Gaza-1988.jpg"},
    {name:"Philippines", capital:"Manila", info:"The Pearl of the Orient", color:33},
    {name:"Qatar", capital:"Doha", info:"The Richest Nation", color:34},
    {name:"Saudi Arabia", capital:"Riyadh", info:"The Land of Two Holy Mosques", color:35,
           url:"https://www.worldatlas.com/r/w1200/upload/76/d1/a8/sa-01.jpg"},
    {name:"Singapore", capital:"Singapore", info:"The Lion City", color:36},
    {name:"South Korea", capital:"Seoul", info:"The Land of Morning Calm", color:37,
           url:"https://www.worldatlas.com/upload/b3/25/fc/kr-01.jpg"},
    {name:"Sri Lanka", capital:"Colombo", info:"The Pearl of the Indian Ocean", color:38,
           url:"https://www.mapsofindia.com/world-map/sri-lanka/sri-lanka-provinces-and-capital-map.jpg"},
    {name:"Syria", capital:"Damascus", info:"The Cradle of Civilization", color:39},
    {name:"Tajikistan", capital:"Dushanbe", info:"The Roof of the World", color:40},
    {name:"Thailand", capital:"Bangkok", info:"The Land of Smiles", color:41},
    {name:"Timor-Leste", capital:"Dili", info:"The Rising Nation", color:42},
    {name:"Turkey", capital:"Ankara", info:"The Bridge Between Continents", color:43},
    {name:"Turkmenistan", capital:"Ashgabat", info:"The Land of White Marble", color:44},
    {name:"United Arab Emirates", capital:"Abu Dhabi", info:"The Land of Skyscrapers", color:45,
          url:"https://www.worldatlas.com/upload/af/06/8b/ae-01.jpg"},
    {name:"Uzbekistan", capital:"Tashkent", info:"The Land of Silk Roads", color:46},
    {name:"Vietnam", capital:"Hanoi", info:"The Land of Dragons", color:47},
    {name:"Yemen", capital:"Sana'a", info:"The Ancient Arabian Jewel", color:48},
    {name:"Taiwan", capital:"Taipei", info:"The Asian Tiger", color:49},
    {name:"Russia", capital:"Moscow", info:"The Land of Tsars", color:50,
          url:"https://www.freeworldmaps.net/russia/russia-physical.jpg"}
]};

const latin = {name:'Latin America', png:'latin', list:[
    {name:"Mexico", capital:"Mexico City", info:"The Land of the Aztecs", color:1,
          url:"https://www.freeworldmaps.net/northamerica/mexico/mexico-map.jpg"},
    {name:"Belize", capital:"Belmopan", info:"The Jewel of the Caribbean", ca:"true", color:2},
    {name:"Costa Rica", capital:"San Jose", info:"The Land of Pura Vida", ca:"true", color:3},
    {name:"El Salvador", capital:"San Salvador", info:"The Land of Volcanoes", ca:"true", color:4,
          url:"https://www.freeworldmaps.net/centralamerica/salvador/salvador-map.jpg"},
    {name:"Guatemala", capital:"Guatemala City", info:"The Heart of the Mayan World", ca:"true", color:5},
    {name:"Honduras", capital:"Tegucigalpa", info:"The Land of Great Depths", ca:"true", color:6},
    {name:"Nicaragua", capital:"Managua", info:"The Land of Lakes and Volcanoes", ca:"true", color:7},
    {name:"Panama", capital:"Panama City", info:"The Bridge of the World", ca:"true", color:8},
    {name:"Argentina", capital:"Buenos Aires", info:"The Land of Tango", color:9},
    {name:"Bolivia", capital:"Sucre", info:"The Heart of South America", color:10},
    {name:"Brazil", capital:"Brasilia", info:"The Land of Samba", color:11},
    {name:"Chile", capital:"Santiago", info:"The Land of Poets", color:12},
    {name:"Colombia", capital:"Bogota", info:"The Land of Coffee", color:13},
    {name:"Ecuador", capital:"Quito", info:"The Land of the Equator", color:14},
    {name:"Guyana", capital:"Georgetown", info:"The Land of Many Waters", color:15},
    {name:"Paraguay", capital:"Asuncion", info:"The Land of Guarani", color:16},
    {name:"Peru", capital:"Lima", info:"The Land of the Incas", color:17},
    {name:"Suriname", capital:"Paramaribo", info:"The Land of Rivers", color:18},
    {name:"Uruguay", capital:"Montevideo", info:"The Switzerland of America", color:19},
    {name:"Venezuela", capital:"Caracas", info:"The Land of Grace", color:20},
    {name:"Cuba", capital:"Havana", info:"The Pearl of the Antilles", ca:"true", color:21},
    {name:"Dominican Republic", capital:"Santo Domingo", info:"The Cradle of the Americas", ca:"true", color:22},
    {name:"Haiti", capital:"Port-au-Prince", info:"The Land of Mountains", ca:"true", color:23},
    {name:"Jamaica", capital:"Kingston", info:"The Land of Wood and Water", ca:"true", color:24},
    {name:"Puerto Rico", capital:"San Juan", info:"The Island of Enchantment", ca:"true", color:25},
    {name:"French Guiana", capital:"Cayenne", info:"The Gateway to Space", color:26},
    {name:"Trinidad and Tobago", capital:"Port of Spain", info:"The Land of Steelpan", color:27,
          url:"https://www.freeworldmaps.net/centralamerica/trinidad/trinidadtobago.jpg"}
]};

const africa = {name:'Africa', png:'africa', list:[
    {name:"Algeria", capital:"Algiers", info:"The Land of the Sahara", color:1},
    {name:"Angola", capital:"Luanda", info:"The Land of Diamonds", color:2},
    {name:"Benin", capital:"Porto-Novo", info:"The Birthplace of Voodoo", color:3},
    {name:"Botswana", capital:"Gaborone", info:"The Land of Diamonds", color:4},
    {name:"Burkina Faso", capital:"Ouagadougou", info:"The Land of Upright People", color:5},
    {name:"Burundi", capital:"Gitega", info:"The Heart of Africa", color:6},
    {name:"Cameroon", capital:"Yaoundé", info:"Africa in Miniature", color:7},
    {name:"Central African Republic", capital:"Bangui", info:"The Land of Natural Beauty", color:8,
          url:"https://www.freeworldmaps.net/africa/centralafrica/centralafrica-physical.jpg"},
    {name:"Chad", capital:"N'Djamena", info:"The Babel Tower of the Sahel", color:9},
    {name:"Djibouti", capital:"Djibouti", info:"The Land of Salt", color:10},
    {name:"Egypt", capital:"Cairo", info:"The Gift of the Nile", color:11},
    {name:"Equatorial Guinea", capital:"Malabo", info:"The Land of Bioko", color:12},
    {name:"Eswatini", capital:"Mbabane", info:"Africa's Last Absolute Monarchy", key:"swaziland", color:13},
    {name:"Ethiopia", capital:"Addis Ababa", info:"The Land of Origins", color:14},
    {name:"Gabon", capital:"Libreville", info:"The Land of Forests", color:15},
    {name:"Gambia", capital:"Banjul", info:"The Smiling Coast of Africa", color:16},
    {name:"Ghana", capital:"Accra", info:"The Land of Gold", color:17},
    {name:"Guinea", capital:"Conakry", info:"The Land of Rivers", color:18},
    {name:"Guinea-Bissau", capital:"Bissau", info:"The Land of Two Rivers", key:"guineabissau", color:19},
    {name:"Ivory Coast (Côte d'Ivoire)", capital:"Yamoussoukro", info:"The Land of Elephants", key:"ivorycoast", color:20},
    {name:"Kenya", capital:"Nairobi", info:"The Land of Safaris", color:21},
    {name:"Lesotho", capital:"Maseru", info:"The Kingdom in the Sky", color:22},
    {name:"Liberia", capital:"Monrovia", info:"The Land of Freedom", color:23},
    {name:"Libya", capital:"Tripoli", info:"The Gateway to the Sahara", color:24},
    {name:"Madagascar", capital:"Antananarivo", info:"The Red Island", color:25},
    {name:"Malawi", capital:"Lilongwe", info:"The Warm Heart of Africa", color:26},
    {name:"Mali", capital:"Bamako", info:"The Land of Timbuktu", color:27},
    {name:"Mauritania", capital:"Nouakchott", info:"The Land of the Desert", color:28},
    {name:"Morocco", capital:"Rabat", info:"The Land of the Atlas", color:29},
    {name:"Mozambique", capital:"Maputo", info:"The Land of Good People", color:30},
    {name:"Namibia", capital:"Windhoek", info:"The Land of the Brave", color:31},
    {name:"Niger", capital:"Niamey", info:"The Land of the Sahara", color:32},
    {name:"Nigeria", capital:"Abuja", info:"The Giant of Africa", color:33},
    {name:"Republic of Congo", capital:"Brazzaville", info:"The Heart of Africa", key:"congo", color:34},
    {name:"Rwanda", capital:"Kigali", info:"The Land of a Thousand Hills", color:35},
    {name:"Senegal", capital:"Dakar", info:"The Land of Teranga", color:36},
    {name:"Sierra Leone", capital:"Freetown", info:"The Land of Mountains", color:37},
    {name:"Somalia", capital:"Mogadishu", info:"The Horn of Africa", color:38},
    {name:"South Africa", capital:"Pretoria", info:"The Rainbow Nation", color:39},
    {name:"South Sudan", capital:"Juba", info:"The World's Newest Nation", color:40},
    {name:"Sudan", capital:"Khartoum", info:"The Land of the Nile", color:41},
    {name:"Tanzania", capital:"Dodoma", info:"The Land of Kilimanjaro", color:42},
    {name:"Togo", capital:"Lomé", info:"The Land of Hospitality", color:43},
    {name:"Tunisia", capital:"Tunis", info:"The Land of Jasmine", color:44},
    {name:"Uganda", capital:"Kampala", info:"The Pearl of Africa", color:45},
    {name:"Zambia", capital:"Lusaka", info:"The Real Africa", color:46},
    {name:"Zimbabwe", capital:"Harare", info:"The Land of Great Zimbabwe", color:47},
    {name:"Western Sahara", capital:"Laayoune", info:"The Land of Sands", color:48},
    {name:"Democratic Republic of the Congo", capital:"Kinshasa", info:"The Land of the Congo River", color:49,
          url:"https://www.freeworldmaps.net/africa/demrepcongo/congo-map.jpg"},
    {name:"Eritrea", capital:"Asmara", info:"The Land of the Red Sea", color:50}
]};

const canada = {name:'Canada', png:'canada', list:[
    {name:"Alberta", capital:"Edmonton", info:"Wild Rose Country", color:1},
    {name:"British Columbia", capital:"Victoria", info:"Beautiful British Columbia", color:2},
    {name:"Manitoba", capital:"Winnipeg", info:"Friendly Manitoba", color:3},
    {name:"New Brunswick", capital:"Fredericton", info:"Picture Province", color:4},
    {name:"Newfoundland and Labrador", capital:"St. John's", info:"The Rock", color:5},
    {name:"Nova Scotia", capital:"Halifax", info:"Canada's Ocean Playground", color:6},
    {name:"Nunavut", capital:"Iqaluit", info:"Our Land, Our Strength", color:7},
    {name:"Ontario", capital:"Toronto", info:"Yours to Discover", color:8},
    {name:"Prince Edward Island", capital:"Charlottetown", info:"Garden of the Gulf", color:9},
    {name:"Quebec", capital:"Quebec City", info:"La Belle Province", color:10},
    {name:"Saskatchewan", capital:"Regina", info:"Land of the Living Skies", color:11},
    {name:"Northwest Territories", capital:"Yellowknife", info:"Land of the Midnight Sun", color:12},
    {name:"Yukon", capital:"Whitehorse", info:"Larger Than Life", color:13}
]};

const china = {name:'China', png:'china', list:[
  {name:"Anhui", type:"Province", capital:"Hefei", info:"Land of Tea and Rivers", color:1},
  {name:"Beijing", type:"Municipality", capital:"Beijing", info:"The Capital of China", color:2},
  {name:"Chongqing", type:"Municipality", capital:"Chongqing", info:"Mountain City", color:3},
  {name:"Fujian", type:"Province", capital:"Fuzhou", info:"The Land of Banyans", color:4},
  {name:"Gansu", type:"Province", capital:"Lanzhou", info:"Corridor of the Silk Road", color:5},
  {name:"Guangdong", type:"Province", capital:"Guangzhou", info:"The Pearl of the South", color:6},
  {name:"Guangxi", type:"Autonomous Region", capital:"Nanning", info:"Land of Ethnic Harmony", color:7},
  {name:"Guizhou", type:"Province", capital:"Guiyang", info:"Village of Clouds", color:8},
  {name:"Hainan", type:"Province", capital:"Haikou", info:"Hawaii of China", color:9},
  {name:"Hebei", type:"Province", capital:"Shijiazhuang", info:"Home of the Great Wall", color:10},
  {name:"Heilongjiang", type:"Province", capital:"Harbin", info:"Ice City", color:11},
  {name:"Henan", type:"Province", capital:"Zhengzhou", info:"The Cradle of Civilization", color:12},
  {name:"Hong Kong", type:"Special Administrative Region", capital:"Hong Kong", info:"Asia's World City", color:13, url:"https://www.hiddenchina.net/img/maps/hongkong.jpg"},
  {name:"Hubei", type:"Province", capital:"Wuhan", info:"The Land of Lakes", color:14},
  {name:"Hunan", type:"Province", capital:"Changsha", info:"Province of the Red Soil", color:15},
  {name:"Inner Mongolia", type:"Autonomous Region", capital:"Hohhot", info:"Grasslands of Freedom", color:16},
  {name:"Jiangsu", type:"Province", capital:"Nanjing", info:"Land of Fish and Rice", color:17},
  {name:"Jiangxi", type:"Province", capital:"Nanchang", info:"Kingdom of Porcelain", color:18},
  {name:"Jilin", type:"Province", capital:"Changchun", info:"Home of Snow and Forests", color:19},
  {name:"Liaoning", type:"Province", capital:"Shenyang", info:"Industrial Heartland", color:20},
  {name:"Macau", type:"Special Administrative Region", capital:"Macau", info:"City of Dreams", color:21},
  {name:"Ningxia", type:"Autonomous Region", capital:"Yinchuan", info:"Oasis of the Yellow River", color:22},
  {name:"Qinghai", type:"Province", capital:"Xining", info:"Land of the Blue Lake", color:23},
  {name:"Shaanxi", type:"Province", capital:"Xi'an", info:"The Ancient Heartland", color:24},
  {name:"Shandong", type:"Province", capital:"Jinan", info:"Land of Confucius", color:25},
  {name:"Shanghai", type:"Municipality", capital:"Shanghai", info:"The Pearl of the Orient", color:26},
  {name:"Shanxi", type:"Province", capital:"Taiyuan", info:"Coal Capital of China", color:27},
  {name:"Sichuan", type:"Province", capital:"Chengdu", info:"Home of the Giant Panda", color:28},
  {name:"Taiwan", type:"Province", capital:"Taipei", info:"The Heart of Asia", color:29},
  {name:"Tianjin", type:"Municipality", capital:"Tianjin", info:"The Port City", color:30},
  {name:"Tibet", type:"Autonomous Region", capital:"Lhasa", info:"Roof of the World", color:31},
  {name:"Xinjiang", type:"Autonomous Region", capital:"Urumqi", info:"Land of Silk Road", color:32},
  {name:"Yunnan", type:"Province", capital:"Kunming", info:"Kingdom of Biodiversity", color:33},
  {name:"Zhejiang", type:"Province", capital:"Hangzhou", info:"Land of Silk and Tea", color:34}
]};

const caribbean = {name:'Caribbean', png:'caribbean', list:[
  {name:"Antigua and Barbuda", capital:"Saint John's", info:"Land of 365 Beaches", color:1,
  url:"https://www.freeworldmaps.net/centralamerica/antigua/antiguabarbuda-map.jpg"},
  {name:"Bahamas", capital:"Nassau", info:"Archipelago of Paradise", color:2},
  {name:"Barbados", capital:"Bridgetown", info:"The Gem of the Caribbean", color:3},
  {name:"Cayman Islands", capital:"George Town", info:"Tax Haven of the Caribbean", color:4,
  url:"https://www.freeworldmaps.net/centralamerica/cayman/cayman-islands.jpg"},
  {name:"Cuba", capital:"Havana", info:"Pearl of the Antilles", color:5},
  {name:"Dominica", capital:"Roseau", info:"Nature Island of the Caribbean", color:6},
  {name:"Dominican Republic", capital:"Santo Domingo", info:"The Land of Firsts", color:7},
  {name:"Grenada", capital:"St. George's", info:"The Spice Isle", color:8},
  {name:"Haiti", capital:"Port-au-Prince", info:"Land of Mountains", color:9},
  {name:"Jamaica", capital:"Kingston", info:"The Island of Reggae", color:10,
  url:"https://www.freeworldmaps.net/centralamerica/jamaica/jamaica-map.jpg"},
  {name:"Puerto Rico", capital:"San Juan", info:"Island of Enchantment", color:11},
  {name:"Saint Kitts and Nevis", capital:"Basseterre", info:"Two Islands, One Paradise", color:12,
  url:"https://www.freeworldmaps.net/centralamerica/stkitts/stkitts.jpg"},
  {name:"Saint Lucia", capital:"Castries", info:"Helen of the West Indies", color:13,
  url:"https://www.freeworldmaps.net/centralamerica/stlucia/stlucia.jpg"},
  {name:"Saint Vincent and the Grenadines", capital:"Kingstown", info:"Jewels of the Antilles", color:14,
  url:"https://www.freeworldmaps.net/centralamerica/stvincent/stvincent.jpg"},
  {name:"Trinidad and Tobago", capital:"Port of Spain", info:"Land of Steelpan and Calypso", color:15,
  url:"https://www.freeworldmaps.net/centralamerica/trinidad/trinidadtobago.jpg"},
  {name:"Guadeloupe", capital:"Basse-Terre", info:"Butterfly Island", color:16},
  {name:"Martinique", capital:"Fort-de-France", info:"Island of Flowers", color:17}
]};

const maps = [africa, asia, canada, caribbean, china, europe, latin, usa];
