const usa = {name:'USA', png:'usa', list:[
    {name:"Alabama", capital:"Montgomery", info:"The Yellowhammer State", color:1},
    {name:"Alaska", capital:"Juneau", info:"The Last Frontier", color:2},
    {name:"Arizona", capital:"Phoenix", info:"The Grand Canyon State", color:3},
    {name:"Arkansas", capital:"Little Rock", info:"The Natural State", color:4},
    {name:"California", capital:"Sacramento", info:"The Golden State", color:5},
    {name:"Colorado", capital:"Denver", info:"The Centennial State", color:6},
    {name:"Connecticut", capital:"Hartford", info:"The Constitution State", color:7},
    {name:"Delaware", capital:"Dover", info:"The First State", color:8},
    {name:"Florida", capital:"Tallahassee", info:"The Sunshine State", color:9},
    {name:"Georgia", capital:"Atlanta", info:"The Peach State", color:10},
    {name:"Hawaii", capital:"Honolulu", info:"The Aloha State", color:11},
    {name:"Idaho", capital:"Boise", info:"The Gem State", color:12},
    {name:"Illinois", capital:"Springfield", info:"The Prairie State", color:13},
    {name:"Indiana", capital:"Indianapolis", info:"The Hoosier State", color:14},
    {name:"Iowa", capital:"Des Moines", info:"The Hawkeye State", color:15},
    {name:"Kansas", capital:"Topeka", info:"The Sunflower State", color:16},
    {name:"Kentucky", capital:"Frankfort", info:"The Bluegrass State", color:17},
    {name:"Louisiana", capital:"Baton Rouge", info:"The Pelican State", color:18},
    {name:"Maine", capital:"Augusta", info:"The Pine Tree State", color:19},
    {name:"Maryland", capital:"Annapolis", info:"The Old Line State", color:20},
    {name:"Massachusetts", capital:"Boston", info:"The Bay State", color:21},
    {name:"Michigan", capital:"Lansing", info:"The Great Lakes State", color:22},
    {name:"Minnesota", capital:"Saint Paul", info:"The North Star State", color:23},
    {name:"Mississippi", capital:"Jackson", info:"The Magnolia State", color:24},
    {name:"Missouri", capital:"Jefferson City", info:"The Show-Me State", color:25},
    {name:"Montana", capital:"Helena", info:"The Treasure State", color:26},
    {name:"Nebraska", capital:"Lincoln", info:"The Cornhusker State", color:27},
    {name:"Nevada", capital:"Carson City", info:"The Silver State", color:28},
    {name:"New Hampshire", capital:"Concord", info:"The Granite State", color:29},
    {name:"New Jersey", capital:"Trenton", info:"The Garden State", color:30},
    {name:"New Mexico", capital:"Santa Fe", info:"The Land of Enchantment", color:31},
    {name:"New York", capital:"Albany", info:"The Empire State", color:32},
    {name:"North Carolina", capital:"Raleigh", info:"The Tar Heel State", color:33},
    {name:"North Dakota", capital:"Bismarck", info:"The Peace Garden State", color:34},
    {name:"Ohio", capital:"Columbus", info:"The Buckeye State", color:35},
    {name:"Oklahoma", capital:"Oklahoma City", info:"The Sooner State", color:36},
    {name:"Oregon", capital:"Salem", info:"The Beaver State", color:37},
    {name:"Pennsylvania", capital:"Harrisburg", info:"The Keystone State", color:38},
    {name:"Rhode Island", capital:"Providence", info:"The Ocean State", color:39},
    {name:"South Carolina", capital:"Columbia", info:"The Palmetto State", color:40},
    {name:"South Dakota", capital:"Pierre", info:"Mount Rushmore State", color:41},
    {name:"Tennessee", capital:"Nashville", info:"The Volunteer State", color:42},
    {name:"Texas", capital:"Austin", info:"The Lone Star State", color:43},
    {name:"Utah", capital:"Salt Lake City", info:"The Beehive State", color:44},
    {name:"Vermont", capital:"Montpelier", info:"The Green Mountain State", color:45},
    {name:"Virginia", capital:"Richmond", info:"The Old Dominion", color:46},
    {name:"Washington", capital:"Olympia", info:"The Evergreen State", color:47},
    {name:"West Virginia", capital:"Charleston", info:"The Mountain State", color:48},
    {name:"Wisconsin", capital:"Madison", info:"The Badger State", color:49},
    {name:"Wyoming", capital:"Cheyenne", info:"The Equality State", color:50}
]};

const europe = {name:'Europe', png:'europe', list:[
    {name:"Albania", capital:"Tiranë", info:"The Land of Eagles", color:1},
    {name:"Andorra", capital:"Andorra la Vella", info:"The Land of Snow", color:2},
    {name:"Armenia", capital:"Yerevan", asia:true, info:"The First Christian Nation", color:3},
    {name:"Austria", capital:"Vienna", info:"The Heart of Europe", color:4},
    {name:"Azerbaijan", capital:"Baku", asia:true, info:"The Land of Fire", color:5},
    {name:"Belarus", capital:"Minsk", info: "The Land of Lakes", color:6},
    {name:"Belgium", capital:"Brussels", info:"The Crossroads of Europe", color:7},
    {name:"Bosnia and Herzegovina", capital:"Sarajevo", key:"bosnia", info: "The Land of Diversity", color:8},
    {name:"Bulgaria", capital:"Sofia", info:"The Land of Roses", color:9},
    {name:"Croatia", capital:"Zagreb", info:"The Pearl of Adriatic", color:10},
    {name:"Cyprus", capital:"Nicosia", info:"Island of Aphrodite", color:11},
    {name:"Czechia", capital:"Prague", info:"Land of Bohemia", color:12},
    {name:"Denmark", capital:"Copenhagen", info:"The Land of Vikings", color:13},
    {name:"Estonia", capital:"Tallinn", info:"The Digital Society" ,color:14},
    {name:"Finland", capital:"Helsinki", info:"The Land of Thousand Lakes", color:15},
    {name:"France", capital:"Paris", info:"The Hexagon", color:16},
    {name:"Georgia", capital:"Tbilisi", asia:true, info:"The Land of Hospitality", color:17},
    {name:"Germany", capital:"Berlin", info:"The Engine of Europe", color:18},
    {name:"Greece" ,capital:"Athens", info:"The Cradle of Civilization", color:19},
    {name:"Hungary", capital:"Budapest", info:"The Land of the Magyars", color:20},
    {name:"Iceland", capital:"Reykjavik", info:"The Land of Fire and Ice", color:21},
    {name:"Ireland", capital:"Dublin", info:"The Emerald Isle", color:22},
    {name:"Italy", capital:"Rome", info:"The Eternal City", color:23},
    {name:"Kosovo", capital:"Pristina", info:"The Youngest European Nation", color:24},
    {name:"Latvia", capital:"Riga", info:"The Land of Amber", color:25},
    {name:"Liechtenstein", capital:"Vaduz", info:"The Microstate of Mountains", color:26,
           url:"https://www.infoplease.com/sites/default/files/i_infopls_com/images/mliecht.gif"},
    {name:"Lithuania", capital:"Vilnius", info:"The Land of Forests", color:27},
    {name:"Luxembourg", capital:"Luxembourg City", info:"The Grand Duchy", color:28},
    {name:"Malta", capital:"Valletta", info:"The Fortress Island", color:29},
    {name:"Moldova", capital:"Chisinau", info:"The Land of Wines", color:30},
    {name:"Montenegro", capital:"Podgorica", info:"The Pearl of the Adriatic", color:31},
    {name:"Netherlands", capital:"Amsterdam", info:"The Low Country", color:32},
    {name:"North Macedonia", capital:"Skopje", info:"The Land of Alexander", key:"macedonia", color:33},
    {name:"Norway", capital:"Oslo", info:"The Land of Fjords", color:34},
    {name:"Poland", capital:"Warsaw", info:"The Heart of Central Europe", color:35},
    {name:"Portugal", capital:"Lisbon", info:"The Land of Explorers", color:36},
    {name:"Romania", capital:"Bucharest", info:"The Land of Dracula", color:37},
    {name:"Serbia", capital:"Belgrade", info:"The Land of Rivers", color:38},
    {name:"Slovakia", capital:"Bratislava", info:"The Land of Castles", color:39},
    {name:"Slovenia", capital:"Ljubljana", info:"The Green Heart of Europe", color:40},
    {name:"Spain", capital:"Madrid", info:"The Land of Passion", color:41},
    {name:"Sweden", capital:"Stockholm", info:"The Land of Midnight Sun", color:42},
    {name:"Switzerland", capital:"Bern", info:"The Land of Alps", color:43},
    {name:"Turkey", capital:"Ankara", info:"The Bridge Between Continents", color:44},
    {name:"Ukraine", capital:"Kyiv", info:"The Breadbasket of Europe", color:45},
    {name:"United Kingdom", capital:"London", info:"The Land of Monarchs", color:46}
]};

const asia = {name:'Asia', png:'asia', list:[
    {name:"Afghanistan", capital:"Kabul", info:"The Graveyard of Empires", color:1},
    {name:"Armenia", capital:"Yerevan", info:"The First Christian Nation", color:2},
    {name:"Azerbaijan", capital:"Baku", info:"The Land of Fire", color:3},
    {name:"Bahrain", capital:"Manama", info:"The Island Kingdom", color:4},
    {name:"Bangladesh", capital:"Dhaka", info:"The Land of Rivers", color:5},
    {name:"Bhutan", capital:"Thimphu", info:"The Land of Happiness", color:6},
    {name:"Brunei", capital:"Bandar Seri Begawan", info:"The Abode of Peace", color:7},
    {name:"Cambodia", capital:"Phnom Penh", info:"The Land of Temples", color:8},
    {name:"China", capital:"Beijing", info:"The Middle Kingdom", color:9},
    {name:"Cyprus", capital:"Nicosia", info:"Island of Aphrodite", color:10},
    {name:"Georgia", capital:"Tbilisi", info:"The Land of Hospitality", color:11},
    {name:"India", capital:"New Delhi", info:"The Land of Diversity", color:12},
    {name:"Indonesia", capital:"Jakarta", info:"The Emerald of the Equator", color:13},
    {name:"Iran", capital:"Tehran", info:"The Land of Persia", color:14},
    {name:"Iraq", capital:"Baghdad", info:"The Cradle of Civilization", color:15},
    {name:"Israel", capital:"Jerusalem", info:"The Holy Land", color:16},
    {name:"Japan", capital:"Tokyo", info:"The Land of the Rising Sun", color:17},
    {name:"Jordan", capital:"Amman", info:"The Land of Petra", color:18},
    {name:"Kazakhstan", capital:"Astana", info:"The Steppe Nation", color:19},
    {name:"Kuwait", capital:"Kuwait City", info:"The Land of Pearls", color:20},
    {name:"Kyrgyzstan", capital:"Bishkek", info:"The Land of Mountains", color:21},
    {name:"Laos", capital:"Vientiane", info:"The Land of a Million Elephants", color:22},
    {name:"Lebanon", capital:"Beirut", info:"The Land of Cedars", color:23},
    {name:"Malaysia", capital:"Kuala Lumpur", info:"Truly Asia", color:24},
    {name:"Maldives", capital:"Malé", info:"The Tropical Paradise", color:25,
           url:"https://as1.ftcdn.net/v2/jpg/04/57/00/82/1000_F_457008282_9W8VRaUDkP9yWT2M2pZmaGF7o7Ovq8j8.jpg"},
    {name:"Mongolia", capital:"Ulaanbaatar", info:"The Land of Eternal Blue Sky", color:26},
    {name:"Myanmar", capital:"Naypyidaw", info:"The Golden Land", color:27},
    {name:"Nepal", capital:"Kathmandu", info:"The Land of Himalayas", color:28},
    {name:"North Korea", capital:"Pyongyang", info:"The Hermit Kingdom", color:29,
           url:"https://www.worldatlas.com/upload/8f/05/35/provinces-of-north-korea-map.png"},
    {name:"Oman", capital:"Muscat", info:"The Jewel of Arabia", color:30},
    {name:"Pakistan", capital:"Islamabad", info:"The Land of the Pure", color:31},
    {name:"Palestine", capital:"East Jerusalem", info:"The Holy Land", color:32,
           url:"https://cdn.britannica.com/17/201417-050-D3316841/vision-Israel-state-West-Bank-Palestinian-Gaza-1988.jpg"},
    {name:"Philippines", capital:"Manila", info:"The Pearl of the Orient", color:33},
    {name:"Qatar", capital:"Doha", info:"The Richest Nation", color:34},
    {name:"Saudi Arabia", capital:"Riyadh", info:"The Land of Two Holy Mosques", color:35,
           url:"https://www.worldatlas.com/r/w1200/upload/76/d1/a8/sa-01.jpg"},
    {name:"Singapore", capital:"Singapore", info:"The Lion City", color:36},
    {name:"South Korea", capital:"Seoul", info:"The Land of Morning Calm", color:37,
           url:"https://www.worldatlas.com/upload/b3/25/fc/kr-01.jpg"},
    {name:"Sri Lanka", capital:"Colombo", info:"The Pearl of the Indian Ocean", color:38,
           url:"https://www.mapsofindia.com/world-map/sri-lanka/sri-lanka-provinces-and-capital-map.jpg"},
    {name:"Syria", capital:"Damascus", info:"The Cradle of Civilization", color:39},
    {name:"Tajikistan", capital:"Dushanbe", info:"The Roof of the World", color:40},
    {name:"Thailand", capital:"Bangkok", info:"The Land of Smiles", color:41},
    {name:"Timor-Leste", capital:"Dili", info:"The Rising Nation", color:42},
    {name:"Turkey", capital:"Ankara", info:"The Bridge Between Continents", color:43},
    {name:"Turkmenistan", capital:"Ashgabat", info:"The Land of White Marble", color:44},
    {name:"United Arab Emirates", capital:"Abu Dhabi", info:"The Land of Skyscrapers", color:45,
          url:"https://www.worldatlas.com/upload/af/06/8b/ae-01.jpg"},
    {name:"Uzbekistan", capital:"Tashkent", info:"The Land of Silk Roads", color:46},
    {name:"Vietnam", capital:"Hanoi", info:"The Land of Dragons", color:47},
    {name:"Yemen", capital:"Sana'a", info:"The Ancient Arabian Jewel", color:48},
    {name:"Taiwan", capital:"Taipei", info:"The Asian Tiger", color:49}
]};